## Numpy Array operations

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing", arr[2:7])
print("With step", arr[1:8:2])
print("Negative indexing", arr[-3])


Basic slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire row", arr_2d[1])
print("Entire column", arr_2d[:,1])

Specific element 6
Entire row [4 5 6]
Entire column [2 5 8]


### Sorting

In [6]:
unsorted = np.array([3,1,4,1,5,9,8])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[3,2]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis = 1))


Sorted Array [1 1 3 4 5 8 9]
Sorted 2D array by column [[1 1]
 [3 2]
 [3 2]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 ==0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [ ]:
mask = numbers > 5
print("Numbers greator than 5: ", numbers[mask])

Numbers greator than 5:  [False False False False False  True  True  True  True  True]


## Fancy indexing vs np.where()

In [ ]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("NP where", numbers[where_result])

[1 3 5]
NP where (array([5, 6, 7, 8, 9]),)


In [10]:
condition = np.where(numbers > 5, numbers *2, numbers)
print(condition)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [13]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))
print(original)
print("\n",with_new_row)

new_column = np.array([[7],[8],[9]])
with_new_col = np.hstack((with_new_row, new_column))
print("\n", with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [14]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, arr > 3)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 3]
